### ISSUE TITLE
cp: cannot copy a directory, '/app', into itself, '/app/node'

### ISSUE THREAD

**Issue by roypen** [flathub/org.freedesktop.Sdk.Extension.node14#3]
Hi,
I have a problem creating Flatpak for electron app using `org.freedesktop.Sdk.Extension.node14`. Flatpack-builder returns the error:

```
Running: /usr/lib/sdk/node14/install-sdk.sh
cp: cannot copy a directory, '/app', into itself, '/app/node'
Error: module node: Child process exited with code 1
```
The problem doesn't exist when using node12 sdk extension

**Comment by gasinvein** [comment]
Are you running `install-sdk.sh` during app build-time? I guess you're not supposed to - instead, just add `/usr/lib/sdk/node14/bin` to `PATH`.
Honestly I didn't ever use those scripts and just copied them over from node12. UPD: Looks like I've adapted them in a wrong way. Fixed.
